// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: activities.sql

package sqlc

import (
	"context"
)

const getActivities = `-- name: GetActivities :many
SELECT id, title, email, created_at, updated_at, deleted_at FROM activities
ORDER BY id DESC
`

func (q *Queries) GetActivities(ctx context.Context) ([]Activity, error) {
	rows, err := q.db.QueryContext(ctx, getActivities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Activity
	for rows.Next() {
		var i Activity
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Email,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
