// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package sqlc

import (
	"database/sql"
)

type Activity struct {
	ID        int64
	Title     sql.NullString
	Email     sql.NullString
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	DeletedAt sql.NullTime
}

type Todo struct {
	ID              int64
	ActivityGroupID sql.NullInt32
	Title           sql.NullString
	IsActive        sql.NullBool
	Priority        sql.NullString
	CreatedAt       sql.NullTime
	UpdatedAt       sql.NullTime
	DeletedAt       sql.NullTime
}
