// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2
// source: todos.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (activity_group_id, title, is_active)
VALUES ($1, $2, $3)
RETURNING id, activity_group_id, title, is_active, priority, created_at, updated_at, deleted_at
`

type CreateTodoParams struct {
	ActivityGroupID sql.NullInt32
	Title           sql.NullString
	IsActive        sql.NullBool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, arg.ActivityGroupID, arg.Title, arg.IsActive)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.ActivityGroupID,
		&i.Title,
		&i.IsActive,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSingleTodos = `-- name: GetSingleTodos :many
SELECT id, activity_group_id, title, is_active, priority, created_at, updated_at, deleted_at FROM todos
WHERE id = $1
`

func (q *Queries) GetSingleTodos(ctx context.Context, id int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getSingleTodos, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.ActivityGroupID,
			&i.Title,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodosByActivity = `-- name: GetTodosByActivity :many
SELECT id, activity_group_id, title, is_active, priority, created_at, updated_at, deleted_at
FROM todos
WHERE ($1::int IS NULL OR activity_group_id = $1)
ORDER BY id DESC
`

func (q *Queries) GetTodosByActivity(ctx context.Context, dollar_1 int32) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, getTodosByActivity, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.ActivityGroupID,
			&i.Title,
			&i.IsActive,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
