version: "3.8"
services:
  restapi:
    container_name: hexagonal-sqlc
    build:
      context: .
      dockerfile: ./docker/restapi.dockerfile
    restart: on-failure
    ports:
      - "3030:3030"
    image: ezizull/hexagonal-sqlc:latest
    volumes:
      - .:/app
    environment:
      - GOPATH=/usr/src/app
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_DBNAME=${POSTGRES_DBNAME}
